// SPDX-License-Identifier: Apache-2.0
/* Copyright 2025 Spice Labs, Inc. & Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License. */

package io.spicelabs.cli;

import java.util.ServiceLoader;
import java.util.concurrent.Callable;

import io.spicelabs.cli.spi.SpiceCommandPlugin;

import picocli.CommandLine.Command;

/**
 * Prints a PowerShell tab-completion script for {@code spice}.
 *
 * <p>picocli generates bash/zsh completion (see {@code generate-completion}) but not
 * PowerShell, so this builds a data-driven completer from a {@code $SpiceCompletions}
 * table of the built-in commands, then splices in each ServiceLoader-discovered plugin's
 * {@link SpiceCommandPlugin#powershellCompletion()} fragment. Plugins on the classpath
 * (e.g. {@code registry}) therefore get PowerShell completion too.
 */
@Command(
    name = "generate-powershell-completion",
    hidden = true,
    description = "Print a PowerShell tab-completion script (includes plugin fragments).")
public class GeneratePowershellCompletion implements Callable<Integer> {

  @Override
  public Integer call() {
    StringBuilder sb = new StringBuilder();
    sb.append(HEADER);
    for (SpiceCommandPlugin plugin : ServiceLoader.load(SpiceCommandPlugin.class)) {
      String fragment;
      String id;
      try {
        id = plugin.id();
        fragment = plugin.powershellCompletion();
      } catch (Throwable t) {
        continue; // a misbehaving plugin must not break completion generation
      }
      if (fragment != null && !fragment.isBlank()) {
        sb.append("\n# plugin: ").append(id == null ? plugin.getClass().getName() : id)
          .append('\n').append(fragment).append('\n');
      }
    }
    sb.append(FOOTER);
    System.out.println(sb);
    return 0;
  }

  // Built-in command tree. Each top-level key maps __sub -> subcommands and each
  // subcommand -> its options. Plugin fragments add their own top-level keys below.
  private static final String HEADER = """
      # spice PowerShell tab completion (generated by `spice generate-powershell-completion`)
      $SpiceCompletions = @{
        survey = @{
          __sub     = @('inventory', 'runtime')
          inventory = @('--output', '--no-upload', '--upload-only', '--threads', '--max-records', '--chunk-size', '--log-level', '--tag-json', '--goat-rodeo-args', '--ginger-args', '--help')
          runtime   = @('--jfr', '--no-upload', '--native-only', '--keep-recording', '--anchor', '--output', '--log-level', '--help')
        }
        pass = @{
          __sub  = @('decode')
          decode = @('--help')
        }
      }
      """;

  private static final String FOOTER = """
      $__spiceCompleter = {
        param($wordToComplete, $commandAst, $cursorPosition)
        $tokens = @($commandAst.CommandElements | ForEach-Object { $_.ToString() })
        $cmd = if ($tokens.Count -ge 2) { $tokens[1] } else { '' }
        $sub = if ($tokens.Count -ge 3) { $tokens[2] } else { '' }
        $candidates = @()
        if (-not $SpiceCompletions.ContainsKey($cmd)) {
          $candidates = @($SpiceCompletions.Keys) + @('--help', '--version')
        } elseif (-not ($SpiceCompletions[$cmd]['__sub'] -contains $sub)) {
          $candidates = @($SpiceCompletions[$cmd]['__sub'])
        } else {
          $candidates = @($SpiceCompletions[$cmd][$sub])
        }
        $candidates | Where-Object { $_ -like "$wordToComplete*" } | ForEach-Object {
          [System.Management.Automation.CompletionResult]::new($_, $_, 'ParameterValue', $_)
        }
      }
      Register-ArgumentCompleter -Native -CommandName spice -ScriptBlock $__spiceCompleter
      Register-ArgumentCompleter -Native -CommandName spice.ps1 -ScriptBlock $__spiceCompleter
      """;
}
