name: Bug
description: Report a defect or unexpected behavior
title: "Env: <staging|production> // <short summary>"
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      options:
        - Staging
        - Production
    validations:
      required: true

  - type: dropdown
    id: repository
    attributes:
      label: spice-labs-inc repository
      options:
        - fennel
        - dashboard
        - daikon
        - ginger-j
        - spice-labs-cli
        - other
    validations:
      required: true

  - type: input
    id: repository_other
    attributes:
      label: Repository (if you selected "other")
      placeholder: e.g. bigtent
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Repository version number
      description: Release/tag/commit SHA, if known.
      placeholder: 1.1.1 (or abc1234)
    validations:
      required: true

  - type: dropdown
    id: auth
    attributes:
      label: Authentication method
      options:
        - Google Auth
        - JWT
        - SSO
        - Email
        - other
    validations:
      required: false

  - type: input
    id: auth_email
    attributes:
      label: Email (if you selected "Email")
      placeholder: name@example.com
    validations:
      required: false

  - type: input
    id: auth_other
    attributes:
      label: Authentication method (if you selected "other")
      placeholder: Describe the authentication method used
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What is the problem?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Log in
        2. Navigate to ...
        3. Observe behavior
    validations:
      required: true

  - type: textarea
    id: current
    attributes:
      label: Current behavior
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Logs, screenshots, URLs, timestamps, etc.
