name: Build and Test

on:
  push:
    branches: ["**"]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21 and GitHub Maven auth
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          server-id: github-spice-labs-goatrodeo,github-spice-labs-ginger
          server-username: ${{ secrets.GH_USERNAME_SG }}
          server-password: ${{ secrets.GH_TOKEN }}

      - name: Install Dependencies and Build
        run: mvn --batch-mode --update-snapshots -DskipTests install

      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots verify
      