name: Build and Test

on:
  push:
    branches: ["**"]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
          cache: maven

      - name: Install Dependencies and Build
        run: mvn --batch-mode --update-snapshots -DskipTests install

      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots verify
      