#This will be the workflow to build and publish the container
# It will be important to watch the git and docker contexts as we are pulling other repos to build
name: Publish The Spice Labs CLI Container Images

on:
  workflow_dispatch:
  push:
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]

env:
  PLATFORMS: linux/amd64, linux/arm64
    
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub and GHCR
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
            platforms: ${{env.PLATFORMS}}


      - name: Checkout with LFS
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/spice-labs-inc/${{ github.event.repository.name }}
            spicelabs/${{ github.event.repository.name }}
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            latest=true
            
      - name: Build and Push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          platforms: ${{env.PLATFORMS}}
          context: .
          push: true
          provenance: mode=max
          sbom: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/spice-labs-inc/${{ github.event.repository.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true