# .github/workflows/test.yml
name: Bash Wrapper Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-tests:
    # matrix of OS and arch
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        arch: [ X64, ARM64 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      # Only continue if the runner's architecture matches the matrix arch
      - name: Check runner arch matches matrix
        if: ${{ matrix.arch == runner.arch }}
        run: echo Running

      # Ensure Docker is installed
      - name: Install Docker on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
      - name: Install Docker on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install --cask docker
          # note: this will install Docker Desktop; ensure it’s started in your self-hosted/macOS runner
      - name: Install Docker CLI on Windows
        if: matrix.os == 'windows-latest'
        run: choco install docker-cli -y

      - name: Verify Docker
        run: docker version

      - name: Make scripts executable
        run: |
          chmod +x spice
          chmod +x spice-labs.sh

      - name: Run bash smoke tests
        run: |
          bats tests/bash.bats
