name: Bash Wrapper Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-tests:
    strategy:
      matrix:
        include:
          # GitHub-hosted x64 runners
          - os: ubuntu-latest
            arch: X64
          - os: macos-latest
            arch: X64
          - os: windows-latest
            arch: X64
          # (Optional) self-hosted or future ARM64 runners
          - os: ubuntu-latest
            arch: ARM64
          - os: macos-latest
            arch: ARM64

    runs-on: ${{ matrix.os }}
    # skip ARM jobs on hosted until you have ARM runners
    if: ${{ matrix.arch == runner.arch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Docker
        run: |
          case "${{ runner.os }}" in
            Linux)   sudo apt-get update && sudo apt-get install -y docker.io;;
            macOS)   brew install --cask docker;;
            Windows) choco install docker-cli -y;;
          esac

      - name: Verify Docker
        run: docker version

      - name: Make scripts executable
        run: chmod +x spice spice-labs.sh

      - name: Run Bats smoke tests
        run: bats tests/bash.bats
