# .github/workflows/test.yml
name: Bash Wrapper Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-tests:
    strategy:
      matrix:
        include:
          # Linux x64
          - os: ubuntu-latest
            arch: x64
          # Linux ARM64 (emulated via QEMU)
          - os: ubuntu-latest
            arch: arm64
          # macOS x64
          - os: macos-latest
            arch: x64
          # Windows x64
          - os: windows-latest
            arch: x64

    runs-on: ${{ matrix.os }}
    env:
      # force Docker to pull/run the right platform
      DOCKER_DEFAULT_PLATFORM: linux/${{ matrix.arch }}

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      # On Linux ARM jobs, register QEMU and buildx for emulation
      - name: Set up QEMU (ARM emulation)
        if: matrix.arch == 'arm64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      - name: Set up Docker Buildx
        if: matrix.arch == 'arm64'
        uses: docker/setup-buildx-action@v2

      # Install Docker where needed
      - name: Install Docker on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Install Docker on macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install --cask docker
          # ensure Docker.app is running for self-hosted runners

      - name: Install Docker CLI on Windows
        if: matrix.os == 'windows-latest'
        run: choco install docker-cli -y

      - name: Verify Docker
        run: docker version

      - name: Make scripts executable
        run: chmod +x spice spice-labs.sh

      - name: Run Bash smoke tests
        run: bats tests/bash.bats
