# .github/workflows/test.yml
name: Bash Wrapper Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-tests:
    strategy:
      matrix:
        os: [
          ubuntu-24.04,
          ubuntu-24.04-arm,
        ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Verify Docker
        run: docker version

      - name: Run Bash smoke tests
        run: bats tests/bash.bats
