# .github/workflows/test.yml
name: Bash Wrapper Smoke Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  smoke-tests:
    strategy:
      matrix:
        os: [
          ubuntu-24.04,
          ubuntu-24.04-arm,
          macos-15,
          windows-2025
        ]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Docker on Linux
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Install Docker on macOS
        if: matrix.os == 'macos-15'
        run: |
          brew install --cask docker
          # ensure Docker Desktop is running if using a self-hosted preview agent

      - name: Install Docker CLI on Windows
        if: matrix.os == 'windows-2025'
        run: choco install docker-cli -y

      - name: Verify Docker
        run: docker version

      - name: Make scripts executable
        run: chmod +x spice spice-labs.sh

      - name: Run Bash smoke tests
        run: bats tests/bash.bats
