# .github/workflows/test.yml
name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  bash:
    name: Test Bash wrapper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Run Bats tests
        run: bats tests/bash.bats

  pwsh:
    name: Test PowerShell wrapper
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        pwsh-version: [ '5.x','6.x','7.x' ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PowerShell
        uses: milliewalky/setup-pwsh@v1
        with:
          tag: ${{ matrix.pwsh-version }}

      - name: Run Pester tests
        shell: pwsh
        run: |
          # Pester is pre-installed on GitHub runners
          Invoke-Pester -Output Detailed tests/pester.tests.ps1
